### ISSUE TITLE
virt-manager: unable to boot a LXC container from existing directory

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#138]
Virt-manager:
New Connection - LXC - New VM - Type: LXC, OS Container - rootfs: <an existing directory, i.e. AOSC Base> - config CPU - config RAM - Start Install.

Traceback:

无法完成安装：'内部错误：虚拟机无法启动：fuse: unknown option `'
Unknown failure in libvirt_lxc startup
'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 90, in cb_wrapper
    callback(asyncjob, _args, *_kwargs)
  File "/usr/share/virt-manager/virtManager/create.py", line 2277, in _do_async_install
    guest.start_install(meter=meter)
  File "/usr/share/virt-manager/virtinst/guest.py", line 501, in start_install
    noboot)
  File "/usr/share/virt-manager/virtinst/guest.py", line 416, in _create_guest
    dom = self.conn.createLinux(start_xml or final_xml, 0)
  File "/usr/lib/python2.7/site-packages/libvirt.py", line 3606, in createLinux
    if ret is None:raise libvirtError('virDomainCreateLinux() failed', conn=self)
libvirtError: 内部错误：虚拟机无法启动：fuse: unknown option `'
Unknown failure in libvirt_lxc startup

**Comment by MingcongBai** [comment]
```fuse: unknown option `�'``` Huh...

**Comment by MingcongBai** [comment]
Will you provide the steps to reproduce?

**Comment by MingcongBai** [comment]
Please re-open if reproduced.
