### ISSUE TITLE
certbot, acme: missing dependency requests-toolbelt

### ISSUE THREAD

**Issue by misaka4e21** [AOSC-Dev/aosc-os-abbs#1528]
Bug description
-----------------------
Package `certbot` (or its dependency `acme`) lack dependency `requests-toolbelt>=0.3.0`.

Reproducing steps
---------------------------
1. Install `certbot`.
2. Run command `certbot`.
```
$ certbot
Traceback (most recent call last):
  File "/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-toolbelt>=0.3.0' distribution was not found and is required by acme
```

Update channel(s)
--------------------------
Stable. No overlay enabled.

Package and version
------------------------------
```
Package: certbot
Status: install ok installed
Section: net
Installed-Size: 4156
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: all
Version: 0.26.0
Replaces: letsencrypt
Depends: acme (>= 0.25.1), ca-certs (>= 20180816), configargparse (>= 0.13.0), configobj (>= 5.0.6-2), mock (>= 2.0.0-2), parsedatetime (>= 2.4), pyopenssl (>= 18.0.0), pypsutil (>= 5.4.6), pyrfc3339 (>= 1.1), pythondialog (>= 3.3.0), pytz (>= 2018.5), requests (>= 2.19.1), setuptools (>= 40.0.0), six (>= 1.11.0), zope-component (>= 4.4.1), zope-interface (>= 4.5.0)
Description: A tool to automatically receive and install X.509 certificates to enable TLS on servers
```
```
Package: acme
Status: install ok installed
Section: python
Installed-Size: 1084
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: all
Version: 0.26.1
Depends: mock (>= 2.0.0-2), ndg-httpsclient (>= 0.5.0), pyopenssl (>= 18.0.0), pyrfc3339 (>= 1.1), pytz (>= 2018.5), requests (>= 2.19.1), setuptools (>= 40.0.0), six (>= 1.11.0)
Breaks: letencrypt (<= 0.2.0)
Description: ACME protocol implementation in Python
```

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/f1dc867d3cf5cd45bf10fcd35921ae0268f88b7a. Closing.
