### ISSUE TITLE
retext: run error

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1638]
Bug description
-----------------------

```
 🌝👍 [ ~ ] retext

** (process:20583): WARNING **: 17:17:27.675: Error loading plugin: libhunspell-1.6.so.0: cannot open shared object file: No such file or directory

Using configuration file: /home/sakiiily/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/sbin/retext", line 111, in <module>
    main()
  File "/usr/sbin/retext", line 79, in main
    window = ReTextWindow()
  File "/usr/lib/python3.6/site-packages/ReText/window.py", line 217, in __init__
    availableMarkups = markups.get_available_markups()
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 33, in get_available_markups
    for markup in get_all_markups():
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in get_all_markups
    return [entry_point.load() for entry_point in entry_points]
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in <listcomp>
    return [entry_point.load() for entry_point in entry_points]
  File "/home/sakiiily/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/sakiiily/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/sakiiily/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-markdown-math' distribution was not found and is required by the application
 🌚👎 [ ~ ] 
```

Reproducing steps
---------------------------

run retext

Update channel(s)
--------------------------

testing

Package and version
------------------------------

```
 🌚👎 [ ~ ] apt show retext
Package: retext
Version: 7.0.4-1
Essential: no
Section: editors
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Installed-Size: 901 kB
Depends: desktop-file-utils (>= 0.23), docutils (>= 1:0.14), gconf (>= 3.2.6-3), markdown (>= 2.6.11), pyenchant (>= 2.0.0), pymarkups (>= 3.0.0), pyqt5 (>= 5.11.2-1), xdg-utils (>= 3:1.1.3)
Download-Size: 176 kB
APT-Manual-Installed: yes
APT-Sources: https://repo.aosc.io/debs stable/main all Packages
Description: A simple editor for Markdown and ReStructuredText markup languages

N: There are 3 additional records. Please use the '-a' switch to see them.
```

**Comment by MingcongBai** [comment]
Also affects Stable.

```
mingcongbai@TP20MF [ ~ ] $ retext
Using configuration file: /home/白铭骢/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/bin/retext", line 111, in <module>
    main()
  File "/bin/retext", line 79, in main
    window = ReTextWindow()
  File "/usr/lib/python3.6/site-packages/ReText/window.py", line 217, in __init__
    availableMarkups = markups.get_available_markups()
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 33, in get_available_markups
    for markup in get_all_markups():
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in get_all_markups
    return [entry_point.load() for entry_point in entry_points]
  File "/usr/lib/python3.6/site-packages/markups/__init__.py", line 23, in <listcomp>
    return [entry_point.load() for entry_point in entry_points]
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2347, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-markdown-math' distribution was not found and is required by the application
```
