### ISSUE TITLE
code-server: run error (explosive and testing)

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1798]
``` 
!  ~  code-server /home/sakiiily/Downloads/                                                                                            111ms  Wed Apr 17 14:22:47 2019
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readUInt16BE (buffer.js:1031:5)
    at Function.fromBuffer (nbin.js:1:3411)
    at Function.fromBuffer (nbin.js:1:3563)
    at Function.fromBuffer (nbin.js:1:3563)
    at Object.defineProperty.value (nbin.js:1:2046)
    at r (nbin.js:1:220)
    at nbin.js:1:1019
    at nbin.js:1:1028
    at NativeModule.compile (bootstrap_node.js:616:7)
```
packager:
```
 !  ~  dpkg -s code-server                                                                                                              102ms  Wed Apr 17 14:23:00 2019
Package: code-server
Status: install ok installed
Section: utils
Installed-Size: 28716
Maintainer: sakiiily <sakiiily@aosc.io>
Architecture: amd64
Version: 1.792~vsc1.33.1
Description: Run VS Code on a remote server
```

**Comment by eatradish** [comment]
this is ab3 bug
```
root@explosive-saki-40004 [ bin ] ! ll
total 28M
-rwxr-xr-x 1 root root 28M Apr 17 06:53 code-server*
root@explosive-saki-40004 [ bin ] # cd ..
root@explosive-saki-40004 [ usr ] # ls
bin  share
root@explosive-saki-40004 [ usr ] # cd ..
root@explosive-saki-40004 [ abdist ] # cd ..
root@explosive-saki-40004 [ code-server1.792-vsc1.33.1-linux-x64 ] # ll code-server
-rwxr-xr-x 1 root root 85M Apr 14 05:44 code-server*
```
As you can see, the size of the `code-server` binary is 85MB before copying it to the `"$PKGDIR"/usr/bin` directory. 28MB after copying
