### ISSUE TITLE
gnome-boxes: segfault at libosinfo

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#1942]
Bug description
-----------------------

When launching GNOME Boxes, the application interface freezes and eventually crashes (SIGSEGV).

Reproducing steps
---------------------------

Launch GNOME Boxes.

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

`gnome-boxes` v3.30.3

**Comment by cthbleachbit** [comment]
Stack trace for reference:

```
#0  0x00007ffff7182e5d in osinfo_list_get_nth () at /usr/lib/libosinfo-1.0.so.0
#1  0x000055555561c3d2 in ____lambda71_ ()
#2  0x000055555561c6b5 in _____lambda71__gasync_ready_callback ()
#3  0x0000555555625c26 in boxes_os_database_get_os_by_id_async_ready_wrapper ()
#4  0x00007ffff728cc43 in g_task_return_now () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff728f316 in g_task_return () at /usr/lib/libgio-2.0.so.0
#6  0x000055555562b1b8 in boxes_os_database_get_os_by_id_co ()
#7  0x000055555562b25d in boxes_os_database_get_os_by_id_ready ()
#8  0x0000555555625aca in boxes_os_database_ensure_db_loaded_async_ready_wrapper ()
#9  0x00007ffff728cc43 in g_task_return_now () at /usr/lib/libgio-2.0.so.0
#10 0x00007ffff728f316 in g_task_return () at /usr/lib/libgio-2.0.so.0
#11 0x00005555556273b5 in boxes_os_database_ensure_db_loaded_co ()
#12 0x000055555562743e in ___lambda19_ ()
#13 0x000055555562747f in ____lambda19__boxes_os_database_db_loaded ()
#14 0x00007ffff7e8f105 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff7e7c2a8 in signal_emit_unlocked_R () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff7e80522 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff7e8142f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x0000555555632878 in boxes_os_database_load_co ()
#19 0x0000555555632959 in boxes_os_database_load_ready ()
#20 0x000055555568b13b in boxes_async_launcher_launch_async_ready_wrapper ()
#21 0x00007ffff728cc43 in g_task_return_now () at /usr/lib/libgio-2.0.so.0
#22 0x00007ffff728f316 in g_task_return () at /usr/lib/libgio-2.0.so.0
#23 0x000055555568d2de in boxes_async_launcher_launch_co ()
#24 0x000055555568d347 in _boxes_async_launcher_launch_co_gsource_func ()
#25 0x00007ffff7d1b756 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff7d1d3e8 in g_main_context_iterate.isra () at /usr/lib/libglib-2.0.so.0
#27 0x00007ffff7d1d42c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff727eb8d in g_application_run () at /usr/lib/libgio-2.0.so.0
#29 0x0000555555639be5 in _vala_main ()
#30 0x0000555555639c4c in main ()
```

Proposed fix: introduce `osinfo-db-tools` as dependency of `libosinfo` as required by libosinfo official [website](https://libosinfo.org/download/).
