### ISSUE TITLE
ibus-anthy: FTBFS

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2036]
Bug description
-----------------------

```
Comment is not valid Unicode in /usr/include/anthy/anthy.h line 124
Comment is not valid Unicode in /usr/include/anthy/anthy.h line 125
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 40: invalid start byte

The above exception was the direct cause of the following exception:

SystemError: <class 'UnicodeDecodeError'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 96, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 541, in scanner_main
    blocks = cbp.parse_comment_blocks(ss.get_comments())
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 275, in get_comments
    return self._scanner.get_comments()
SystemError: <method 'get_comments' of 'scanner.SourceScanner' objects> returned a result with an error set
make[2]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: Anthy-9000.gir] Error 1
make[2]: Leaving directory '/var/cache/acbs/build/acbs.ub_drvy5/ibus-anthy-1.5.11/gir'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/var/cache/acbs/build/acbs.ub_drvy5/ibus-anthy-1.5.11'
make: *** [Makefile:454: all] Error 2
```

[acbs-build_1m_9laqu.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3737772/acbs-build_1m_9laqu.log)

Reproducing steps
---------------------------

Build `ibus-anthy`.

Update channel(s)
--------------------------

Stable-Proposed

Package and version
------------------------------

31a4351fad2827852bdb71897949f1800788a6a8

**Comment by LionNatsu** [comment]
Fix `anthy-ut` first and this will be solved naturally.
Hints: iconv them from EUC-JP to UTF-8.

**Comment by MingcongBai** [comment]
This was an issue where `anthy` and `anthy-ut` were confused. It builds just fine as of 778f97e16d76020b889ef0282a7b90d78b08a8c2. Closing.
