### ISSUE TITLE
gdb: Python script syntax error

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#2068]
Bug description
-----------------------
After `coredumpctl gdb` attached to a dump:
```
[Current thread is 1 (Thread 0x7ff06bb7e800 (LWP 15678))]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/libgstreamer-1.0.so.0.1600.0-gdb.py", line 9, in <module>
    from gst_gdb import register
  File "/usr/share/gstreamer-1.0/gdb/gst_gdb.py", line 329
    def print(self, indent, prefix=""):
            ^
SyntaxError: invalid syntax
(gdb)
```

Reproducing steps
---------------------------
I can only reproduce this on a certain dump file.

Update channel(s)
--------------------------
Testing

Package and version
------------------------------
```
lion@Lion-Laptop [ repos ] $  dpkg -S libgstreamer-1.0.so.0.1600.0-gdb.py
gstreamer-1-0: /usr/share/gdb/auto-load/usr/lib/libgstreamer-1.0.so.0.1600.0-gdb.py
lion@Lion-Laptop [ repos ] $ apt list -a gstreamer-1-0
正在列表... 完成
gstreamer-1-0/stable,now 1.16.0 amd64 [已安装，自动]
```

**Comment by MingcongBai** [comment]
Not reproducible here (and I don't have that specific dump file). Closing.
