### ISSUE TITLE
yarn 1.22.3: cannot find module

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#2110]
Bug description
-----------------------

```
root@t-p-saki-4018d [ node_modules ] # yarn
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/yarn/bin/../lib/cli'
Require stack:
- /usr/lib/node_modules/yarn/bin/yarn.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/node_modules/yarn/bin/yarn.js' ]
}
```

Reproducing steps
---------------------------
```
root@t-p-saki-4018d [ yarn@testing-proposed ] # cat spec
VER=1.22.3
SRCTBL="https://github.com/yarnpkg/yarn/archive/v$VER.tar.gz"
CHKSUM="sha256::b7fa32ba6e55918b3e06fff06468bdba897ba7c0789138f18763c0c648dec831"
SUBDIR=.
root@t-p-saki-4018d [ yarn@testing-proposed ] # cat autobuild/build 
mv -v "$SRCDIR"/yarn-$PKGVER.{bin,tar.gz}

npm i -g --user root --prefix="$PKGDIR" "$SRCDIR"/yarn-$PKGVER.tar.gz
rm -rfv "$PKGDIR"/etc/
```

Update channel(s)
--------------------------

Testing-proposed

Package and version
------------------------------

yarn 1.22.3

**Comment by eatradish** [comment]
It looks like `https://github.com/yarnpkg/yarn/archive/v1.22.3.tar.gz` cannot be used with ` npm i -g --user root --prefix="$ PKGDIR" "$SRCDIR"/yarn-$PKGVER.tar.gz` to install, and 1.22.3 seems to be just a fix for the Windows version (their tag page only has the .msi binary distribution file)

**Comment by eatradish** [comment]
Closing.
