### ISSUE TITLE
netease-cloud-music-gtk: cannot connect to network

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#2373]
Bug description
-----------------------

```
➜  blog-source git:(master) RUST_BACKTRACE=full /usr/bin/netease-cloud-music-gtk
thread 'async-std/runtime' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', /var/cache/acbs/build/acbs.htnuoyx2/rustc-1.46.0-src/src/libstd/macros.rs:thread 'async-std/runtime13:' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', 23
stack backtrace:
/var/cache/acbs/build/acbs.htnuoyx2/rustc-1.46.0-src/src/libstd/macros.rs:13:23
   0:     0x563e3b023a11 - <unknown>
   1:     0x563e3af0e7ac - <unknown>
   2:     0x563e3b023046 - <unknown>
   3:     0x563e3b022a30 - <unknown>
   4:     0x563e3b0220f1 - <unknown>
   5:     0x563e3ae3c7c6 - <unknown>
   6:     0x563e3aeb959a - <unknown>
   7:     0x563e3aed14cc - <unknown>
   8:     0x563e3adfe76e - <unknown>
   9:     0x563e3af00a32 - <unknown>
  10:     0x563e3aeffb1c - <unknown>
  11:     0x563e3b031cda - <unknown>
  12:     0x7efc9d1e6102 - start_thread
  13:     0x7efc9d128bdf - __GI___clone
  14:                0x0 - <unknown>
stack backtrace:
   0:     0x563e3b023a11 - <unknown>
   1:     0x563e3af0e7ac - <unknown>
   2:     0x563e3b023046 - <unknown>
   3:     0x563e3b022a30 - <unknown>
   4:     0x563e3b0220f1 - <unknown>
   5:     0x563e3ae3c7c6 - <unknown>
   6:     0x563e3aeb959a - <unknown>
   7:     0x563e3ae2ec78 - <unknown>
   8:     0x563e3af00a32 - <unknown>
   9:     0x563e3aeffb1c - <unknown>
  10:     0x563e3b031cda - <unknown>
  11:     0x7efc9d1e6102 - start_thread
  12:     0x7efc9d128bdf - __GI___clone
  13:                0x0 - <unknown>
thread 'async-std/runtime' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', /var/cache/acbs/build/acbs.htnuoyx2/rustc-1.46.0-src/src/libstd/macros.rs:13:23
stack backtrace:
   0:     0x563e3b023a11 - <unknown>
   1:     0x563e3af0e7ac - <unknown>
   2:     0x563e3b023046 - <unknown>
   3:     0x563e3b022a30 - <unknown>
   4:     0x563e3b0220f1 - <unknown>
   5:     0x563e3ae3c7c6 - <unknown>
   6:     0x563e3aeb959a - <unknown>
   7:     0x563e3ae2ec78 - <unknown>
   8:     0x563e3af00a32 - <unknown>
   9:     0x563e3aeffb1c - <unknown>
  10:     0x563e3b031cda - <unknown>
  11:     0x7efc9d1e6102 - start_thread
  12:     0x7efc9d128bdf - __GI___clone
  13:                0x0 - <unknown>
thread 'async-std/runtime' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', /var/cache/acbs/build/acbs.htnuoyx2/rustc-1.46.0-src/src/libstd/macros.rs:13:23
stack backtrace:
   0:     0x563e3b023a11 - <unknown>
   1:     0x563e3af0e7ac - <unknown>
   2:     0x563e3b023046 - <unknown>
   3:     0x563e3b022a30 - <unknown>
   4:     0x563e3b0220f1 - <unknown>
   5:     0x563e3ae3c7c6 - <unknown>
   6:     0x563e3aeb959a - <unknown>
   7:     0x563e3ae2ec78 - <unknown>
   8:     0x563e3af00a32 - <unknown>
   9:     0x563e3aeffb1c - <unknown>
  10:     0x563e3b031cda - <unknown>
  11:     0x7efc9d1e6102 - start_thread
  12:     0x7efc9d128bdf - __GI___clone
  13:                0x0 - <unknown>

```

Steps to reproduce
---------------------------

Open netease-cloud-music-gtk

Update channel(s)
--------------------------

amd64, t-p

Package and version
------------------------------

```
➜  blog-source git:(master) dpkg -s netease-cloud-music-gtk 
Package: netease-cloud-music-gtk
Status: install ok installed
Section: sound
Installed-Size: 4396
Maintainer: liushuyu <liushuyu@aosc.io>
Architecture: amd64
Version: 1.1.2-1
Depends: openssl (>= 1.1.1g-3), curl (>= 7.68.0-4), gstreamer-1-0 (>= 1.16.2-1), atk (>= 2.34.1), gdk-pixbuf (>= 2.38.2-1), gst-plugins-bad-1-0 (>= 1.16.2-2), gst-plugins-good-1-0 (>= 1.16.2-1), gst-plugins-ugly-1-0 (>= 1.16.2-1), gst-libav-1-0 (>= 1.16.2), osdlyrics (>= 20190407)
Description: An unofficial client for Netease Cloud Music
```

**Comment by liushuyu** [comment]
The backtrack is totally useless, no relevant information could be deduced.

Next time, please make a build with `ABSTRIP=0` so that the backtrack information is actually useful.

**Comment by eatradish** [comment]
Fixed on enable debug symbols, closing...

**Comment by MingcongBai** [comment]
@eatradish Could be worth it to open an issue online about this as well.
