### ISSUE TITLE
nodejs: npm crashes

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#319]
Reproduce every time.

```
lion [ website-site-ng@develop ] $ npm search redis
npm ERR! Linux 4.6.3-aosc-main
npm ERR! argv "/usr/bin/node" "/bin/npm" "search" "redis"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5

npm ERR! Cannot read property '_updated' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

  730649 ms: Mark-sweep 903.5 (1324.7) -> 878.3 (1300.1) MB, 801.4 / 0 ms [allocation failure] [GC in old space requested].
  731584 ms: Mark-sweep 878.3 (1300.1) -> 878.3 (1298.1) MB, 934.5 / 0 ms [allocation failure] [GC in old space requested].
  732454 ms: Mark-sweep 878.3 (1298.1) -> 878.2 (1291.1) MB, 870.8 / 0 ms [last resort gc].
  733331 ms: Mark-sweep 878.2 (1291.1) -> 878.2 (1285.1) MB, 877.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x258b103c9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x8d6fa4dc850] (this=0x258b10304189 <undefined>,string=0x1211cd744419 <Very long string[188908744]>,encoding=0x258b103d7a49 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x8d6fa4ba476] (this=0x297ae16e68d9 <JS Function Buffer (SharedFunctionInfo 0x258b103e2f51)>,value=0x1211cd744419 <Very long string[188908744]>,encodingOrOffset=0x258b10...                                  

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory                                    
 1: node::Abort() [npm]                                                                                                
 2: 0x555925461eee [npm]                                                                                              
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]                                                        
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]                                                
 5: 0x5559255f3131 [npm]                                                                                              
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]                                                                                                                      
 7: 0x555924f79fa0 [npm]                                                                                              
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]                                                          
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x555924fc65f2 [npm]
14: 0x555924fdee29 [npm]
15: 0x8d6fa00961b
中止 (コアダンプ)
lion [ website-site-ng@develop ] !
```

btw, I found this.

```
lion [ website-site-ng@develop ] $ g
位于分支 develop
您的分支与上游分支 'origin/develop' 一致。
未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）

        npm-debug.log

提交为空，但是存在尚未跟踪的文件（使用 "git add" 建立跟踪）
lion [ website-site-ng@develop ] $ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'search', 'redis' ]
2 info using npm@3.10.5
3 info using node@v6.3.0
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://npmreg.mirrors.ustc.edu.cn/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://npmreg.mirrors.ustc.edu.cn/-/all
9 info updateIndex /home/lion/.npm/npmreg.mirrors.ustc.edu.cn/-/all/.cache.json
10 verbose correctMkdir /home/lion/.npm correctMkdir not in flight; initializing
11 verbose stack TypeError: Cannot read property '_updated' of undefined
11 verbose stack     at /usr/lib/node_modules/npm/lib/cache/update-index.js:61:26
11 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
11 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
12 verbose cwd /home/lion/develop/aosc/website/website-site-ng
13 error Linux 4.6.3-aosc-main
14 error argv "/usr/bin/node" "/bin/npm" "search" "redis"
15 error node v6.3.0
16 error npm  v3.10.5
17 error Cannot read property '_updated' of undefined
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]
lion [ website-site-ng@develop ] $ 
```

**Comment by MingcongBai** [comment]
Updating to npm 3.10.7 did not seem to help (per my build). I will open an upstream issue soon.

**Comment by MingcongBai** [comment]
This is actually due to the package json's size exceeding the memory limit of `npm`.

See https://github.com/npm/npm/issues/3867.
