### ISSUE TITLE
geary & Lollypop missing libgpgme-pthread.so.11

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#505]
`bobcao3@bobcao3 [ ~ ] $ geary
geary: error while loading shared libraries: libgpgme-pthread.so.11: cannot open shared object file: No such file or directory
bobcao3@bobcao3 [ ~ ] ? apt search gpgme
Sorting... Done
Full Text Search... Done
gpgme/os-amd64,now 1.8.0 amd64 [installed,automatic]
  A C wrapper library for GnuPG

gpgmepp/os-amd64 16.08.3 amd64 [residual-config]
  KDE Framework providing KDE/C++ bindings for GPGME

pygpgme/os-amd64 0.3-2 amd64
  Python bindings for GPGME

bobcao3@bobcao3 [ ~ ] $ whereis libgpgme-pthread.so.11
libgpgme-pthread.so:
bobcao3@bobcao3 [ ~ ] $ dpkg -L gpgme | grep pthread
bobcao3@bobcao3 [ ~ ] ! 
`

**Comment by bobcao3** [comment]
As for lollypop:

bobcao3@bobcao3 [ ~ ] $ lollypop
** (lollypop:13947): WARNING **: Failed to load shared library 'libtotem-plparser.so.18' referenced by the typelib: libgpgme-pthread.so.11: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 182, in do_startup
    self.init()
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 158, in init
    self.__parser = TotemPlParser.Parser.new()
GLib.Error: g-invoke-error-quark: Could not locate totem_pl_parser_new: libgpgme-pthread.so.11: cannot open shared object file: No such file or directory (1)
