### ISSUE TITLE
blueberry: fails to start with "no such file or directory"

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#609]
LC_ALL=POSIX blueberry
Warning: DE could not be detected!

(blueberry.py:2661): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry.py", line 35, in on_activate
    self.create_window()
  File "/usr/lib/blueberry/blueberry.py", line 154, in create_window
    self.adapter_name_entry.set_text(self.get_default_adapter_name())
  File "/usr/lib/blueberry/blueberry.py", line 231, in get_default_adapter_name
    output = subprocess.check_output(["bt-adapter", "-i"]).strip()
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by liushuyu** [comment]
>output = subprocess.check_output(["bt-adapter", "-i"]).strip()

This line caused problem. You can try the command `bt-adapter -i` yourself, and see if you have `bt-adapter` or not

**Comment by butangmucat** [comment]
bt-adapter: command not found. Missing dependency?

**Comment by MingcongBai** [comment]
@butangmucat Seems like it's from bluez, maybe a packaging fault.

**Comment by butangmucat** [comment]
As of blueberry 1.1.10-1, not fixed.
