### ISSUE TITLE
mock: requires funcsigs>=1

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#685]
```
lmy441900@junde-dell-vostro [ ~ ] $ certbot
Traceback (most recent call last):
  File "/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs>=1' distribution was not found and is required by mock
```

`funcsigs` is now `0.4`.

**Comment by lmy441900** [comment]
Fixing this issue in 3c2edf7524152098096317bd9e16c3584f6d1af9, which should be pushed in August update.
