### ISSUE TITLE
qscintilla: rebuild for adding Qt4 Python APIs

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#863]
Couldn't load plugin 'processing' 

ImportError: No module named Qsci 
Traceback (most recent call last):
  File "/usr/share/qgis/python/qgis/utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 29, in 
    from processing.tools.general import *              # NOQA
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 31, in 
    from processing.core.Processing import Processing
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 61, in 
    from processing.algs.r.RAlgorithmProvider import RAlgorithmProvider
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/r/RAlgorithmProvider.py", line 35, in 
    from processing.gui.EditScriptAction import EditScriptAction
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/gui/EditScriptAction.py", line 29, in 
    from processing.gui.ScriptEditorDialog import ScriptEditorDialog
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/gui/ScriptEditorDialog.py", line 51, in 
    os.path.join(pluginPath, 'ui', 'DlgScriptEditor.ui'))
  File "/usr/lib/python2.7/site-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 159, in 
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/gui/ScriptEdit.py", line 35, in 
    from qgis.PyQt.Qsci import QsciScintilla, QsciLexerPython, QsciAPIs
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/qgis/PyQt/Qsci.py", line 26, in 
    from PyQt4.Qsci import *
  File "/usr/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named Qsci

Python version: 2.7.14 (default, Nov 17 2017, 22:30:03) [GCC 7.2.0 20170814 (AOSC OS, Core)] 
QGIS version: 2.18.14 Las Palmas, exported 

Python Path:
/usr/share/qgis/python
/home/gumble/.qgis2/python
/home/gumble/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7/site-packages/netsnmp_python-1.0a1-py2.7-linux-x86_64.egg
/usr/lib/python27.zip
/usr/lib/python2.7
/usr/lib/python2.7/plat-linux2
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/lib/python2.7/site-packages
/usr/lib/python2.7/site-packages/gtk-2.0
/usr/lib/python2.7/site-packages/wx-3.0-gtk3
/home/gumble/.qgis2//python

**Comment by MingcongBai** [comment]
Note, as this is an issue with a current `testing`/`staging` package, marking `to-staging`.

**Comment by MingcongBai** [comment]
Funnily enough it simply SIGILLs on my laptop... Could someone else look into this?

**Comment by LionNatsu** [comment]
`LD_PRELOAD=/usr/lib/libgdal.so` fixes
`/usr/lib/python2.7/site-packages/osgeo/_gdal.so: undefined symbol: VSICurlClearCache`

I got `ImportError: No module named Qsci` then.

**Comment by LionNatsu** [comment]
It imports PyQt4.Qsci, which should be installed with `qscintilla`.

But our `qscintilla` generate(?) *only qt5 APIs* (for both python 2 and 3).
